nome = str(input('Digite seu nome completo'))
print('analisando o seu nome...')
print('seu nome em maiúsculo é {}'.format(nome.upper()))
print('seu nome em minúsculo é {}'.format(nome.lower()))
print('seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
#print('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
