algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print ('Só tem aspaços?', algo.isspace())
print('É um numero? ', algo.isnumeric())
print('É alfabetico? ', algo.isalpha())
print('É alfanumerico? ', algo.isalnum())
print('Esta em Maiuscula? ', algo.isupper())
print('Esta em minuscula? ', algo.islower())
print('Esta capitalizada? ', algo.istitle())